### ISSUE TITLE
Acknowledgement_guidelines need to add preferred KBase acknowledgement text

### ISSUE THREAD

**Issue by psdehal** [kbase/project_guides#11]
The exact KBase acknowledgement statement text that can be used in papers should be added to the [Acknowledgment_guidelines.md](https://github.com/kbase/project_guides/blob/master/Acknowledgment_guidelines.md) doc

**Comment by fperez** [comment]
Pinging @aparkin: do you have a reference text you'd like to use for this?

**Comment by nlharris** [comment]
The acknowledgement text in the latest version says:
When writing a paper that cites KBase in any way, you should acknowledge KBase funding as follows: “This work supported by the Office of Science, Office of Biological and Environmental Research, of the US Department of Energy under Contract DE-AC02-06CH1135, as part of the DOE Systems Biology Knowledgebase.”
but @bobcottingham  said that was wrong and that the acknowledgement should be:
This work is supported as part of the Genomic Sciences Program DOE Systems Biology Knowledgebase (KBase) funded by the U.S. Department of Energy, Office of Science, Office of Biological and Environmental Research under Award Numbers DE-AC02-05CH11231, DE-AC02-06CH11357, DE-AC05-00OR22725, and DE-AC02-98CH10886.

**Comment by fperez** [comment]
#51 has been merged with actual text from @aparkin. Adam, can you confirm that text is OK so we can close this issue? If not, I'll fine-tune as needed until we agree.

**Comment by nlharris** [comment]
Hey, should more of this acknowledgement text (not just the funding statement) be added to http://kbase.us/acknowledgements/?

**Comment by nlharris** [comment]
This is done and can be closed.

**Comment by fperez** [comment]
thanks, closing!
