### ISSUE TITLE
who approves kbase dev accts

### ISSUE THREAD

**Issue by kkellerlbl** [kbase/project_guides#22]
I think those approvals are handled by a group at ANL.  Dan Olson would be our primary contact to that group, I believe (but please correct me if I'm wrong).

Referenced here: /Developer_deployment.md#new-developer-checklist

**Comment by kkellerlbl** [comment]
Err, here: https://github.com/kbase/project_guides/blob/master/Developer_deployment.md#new-developer-checklist

**Comment by fperez** [comment]
Pinging @olsonanl: Dan, should we indeed list you as primary contact for that in the docs?

**Comment by danielolson5** [comment]
I'd prefer it if we simply use help@kbase.us and let the ticket routing handle this instead of listing individuals.  

Btw, my github username is dolson.  olsonanl is Bob Olson.  

Dan

**Comment by fperez** [comment]
Sorry about the username confusion, @danielolson5!

@kkellerlbl, would you make an edit to the file with the `help@kbase` reference?

**Comment by kkellerlbl** [comment]
Just did a PR.  Let me know if it looks ok.

**Comment by fperez** [comment]
Great! Further comments in there.
