### ISSUE TITLE
Acknowledging KBase support: contradictory statements?

### ISSUE THREAD

**Issue by mdejongh** [kbase/project_guides#24]
These two statements seem to be in contradiction:
Under general guidelines:
"6. Using KBase as part of your own scientific research **does not require KBase funding acknowledgement**."

Under classes of outputs:
"3. Papers that use KBase should cite the main KBase paper, if the science was directly supported by KBase. But if the use was by a KBase supported person, it **should also cite KBase support**."

**Comment by aparkin** [comment]
I think 3 was was supposed to achieve something like...
3. Papers that use KBase should cite the main KBase paper _and acknowledge KBase funding_, if the science/technology was directly supported by KBase as part of the agreed upon deliverables of KBase. 

I assume the point is that we should not be supporting activities not agreed upon by the executive ultimately.

**Comment by mdejongh** [comment]
That is a helpful clarification.

**Comment by fperez** [comment]
Hi @mdejongh, would you be willing to make a small PR with this clarification in the docs?

**Comment by mdejongh** [comment]
OK

**Comment by fperez** [comment]
Great, thanks!
